<template>
   <div> 
       <button class="btn btn-primary" @click="topic =1 ">Provide/Inject</button> &nbsp;
       <button class="btn btn-primary" @click="topic =2 ">Props</button>&nbsp;
       <button class="btn btn-primary" @click="topic =3 ">Emits</button>&nbsp;
       <button class="btn btn-primary" @click="topic =4 ">V-model</button>&nbsp;
       <button class="btn btn-primary" @click="topic =5 ">Slot</button>&nbsp;
       <button class="btn btn-primary" @click="topic =6 ">Slot props</button>&nbsp;
       <button class="btn btn-primary" @click="topic =7 ">ChildComponentStyle</button>&nbsp;
       <button class="btn btn-primary" @click="topic =8 ">DynamicComponent</button>&nbsp;
       <button class="btn btn-primary" @click="topic =9 ">Teleport</button>&nbsp;
       <!--How to handle http request in vue-->
       <button class="btn btn-primary" @click="topic =10 ">HTTPRequest</button>&nbsp;
       <button class="btn btn-primary" @click="topic =11 ">Life Cycle</button>&nbsp;
       <button class="btn btn-primary" @click="topic =12 ">TemplateRef</button>&nbsp;
       <div v-if="topic=== 1">      
       <h2>Login User {{this.userName}}</h2>
      </div>
      
      <div v-if="topic === 2">
        <!-- adding property  in child component-->
        <GreetVue username='Ankit' heroName='Ajay'/>
        <GreetVue username= 'Rahul' heroName='salman'/>
        <GreetVue username = 'Roshan' heroName='sarukh'/>
        <!--syntax if we are using data propery-->
        <GreetVue :username = 'userName' :heroName='heroName'/>
       
        <Article id="my-article" title='Post1' :likes="50" :isPublished="true"/>
        <Article title='Post2' :likes="500" :isPublished="false"/>
      </div>
      
      <div v-if="topic === 3">
        <!--send data back to the parent component-->
        <button @click="showPopUp=true" >Open popUp</button>
        <!-- getting the event generated by  popUp component-->
        <PopUp v-if="showPopUp" @close="closePopUp"/>
        <!--Using custom field v-model directive -->
        </div>
        

      <div v-if="topic==4">
        <InputVue v-model="name"/>
        <h2>{{name}}</h2>
      </div>

      <div v-if="topic === 5">
        <Card><h2>Content 1</h2></Card>
        <Card><h2>Content 2</h2></Card>
        <Card> <h2>Content3</h2></Card>
        <Card>
         <template v-slot:header>
          <h3>Header</h3>
         </template>
        <div>
          <img src="https://picsum.photos/200/300"/>
        </div>        
         <template v-slot:footer>
          <button type="button" class="btn btn-primary">View</button>
         </template>
        </Card>
      </div>

      <div v-if="topic===6">
        <!-- <NamedList/> -->
        <NamedList>
           <template v-slot:default="slotProps">
           <h2>{{slotProps.firstName}} {{slotProps.lastName}}</h2>
        </template>
      </NamedList>

      <NamedList>
           <template v-slot:default="slotProps">
           <h2>{{slotProps.lastName}} {{slotProps.firstName}}</h2>
        </template>
      </NamedList>
 
      </div>

      <div v-if="topic === 7">
          <h4>App component</h4>
          <ChildComponent/>
          <!-- <ChildComponent>
            <h4>Child Component</h4>
          </ChildComponent> -->
      </div>

      <div v-if="topic === 8">
        <hr/>
        <button class="btn btn-success" @click="activeTab = 'TabA'" >TabA</button>
        <button class="btn btn-success" @click="activeTab = 'TabB'">TabB</button>
        <button class="btn btn-success" @click="activeTab = 'TabC'">TabC</button>
         <hr/>
         <keep-alive>
          <component :is="activeTab"></component>
        </keep-alive>
            <!-- <TabA v-if="activeTab === 'TabA'"/>
            <TabB v-if="activeTab === 'TabB'"/>
            <TabC  v-if="activeTab === 'TabC'"/> -->
      </div>
     <!-- Teleport component-->
      <div v-if="topic === 9">
        <Teleport to="#portal">
           <Portal/>
         </Teleport>
      </div>

      <div v-if="topic === 10">
        <Posts/>
      </div>

      <div v-if="topic === 11">
        <LifeCycleParent/>
      </div>

      <div v-if="topic === 12">
        <TemplateRefs/>
      </div>


  </div>
</template>

<script>
import GreetVue from './components/Greet';
import Article from './components/Article'
import PopUp from './components/PopUp'
import InputVue from './components/Input';
import Card from './components/Card.vue';
import NamedList from './components/NamedList.vue';
import ChildComponent from './components/ChildComponent.vue';
import TabA from './components/TabA.vue';
import TabB from './components/TabB.vue';
import TabC from './components/TabC.vue';
import Portal from './components/Portal.vue';
import Posts from './components/Posts.vue';
import LifeCycleParent from './components/LifeCycleParent.vue';
import TemplateRefs from './components/TemplateRefs.vue';


export default {
  
  name: 'App',
  components: {
    GreetVue,
    Article,
    PopUp,
    InputVue,
    Card,
    NamedList,
    ChildComponent,
    TabA,
    TabB,
    TabC,
    Portal,
    Posts,
    LifeCycleParent,
    TemplateRefs
},
  data(){
    return {
      topic:2,
      userName:"manu",
      heroName:'tusar',
      showPopUp:false,
      name:'',
      activeTab:''
    }
  },
  methods:{
    closePopUp(val){
      this.showPopUp = false;
      console.log("message:::",val)
    }
  },
  provide(){
    return {
      userName: this.userName
    }
  }

}
</script>

<style scoped>

#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
h4{
  color:blue 
}
</style>
